[package]
name = "rrh"
version = "0.1.0"
edition = "2024"

[lib]
name = "rrh"
path = "src/lib.rs"

[[bin]]
name = "rrh"
path = "src/main.rs"

[dependencies]
env_logger = "0.11.8"
thiserror = "2.0.12"
tokio = "1.44.2"
