name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - run: cargo build --release

      - uses: softprops/action-gh-release@v2
        with:
          files: target/release/rrh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

